---
# This role installs httpd and put GIT repo to /var/www/html/

- name: Install http
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - php
    - php-mysql
    - git

- name: http service state
  service: name=httpd state=started enabled=yes

- name: Copy the code from repository
  git: repo={{ repository }} version={{ webapp_version }} dest=/var/www/html/
